#!/usr/bin/env python

from sys import argv, stderr
from makefile2dot import makefile2dot

if len(argv) > 1:
    print(stderr, 'Usage:\n\tmakefile2dot <Makefile >out.dot or')
    print(stderr, '\n\tmakefile2dot <Makefile |dot -Tpng > out.png')
else:
    makefile2dot()
