#!/usr/bin/env python

"""
Command line. See makefile2dot --help.
"""

import argparse
from makefile2dot import makefile2dot

PARSER = argparse.ArgumentParser(description="Stuff")
PARSER.add_argument('--direction', dest='direction', default="BT",
                    help="direction to draw graph ('BT', 'TB', 'LR', or 'RL')")

PARSER.add_argument('--output', '-o', dest='output', default="",
                    help="Output file name (default: stdout).")

PARSER.add_argument('--view', '-v', action='store_true',
                    help="View the graph (disables output)")

ARGS = PARSER.parse_args()

makefile2dot(direction=ARGS.direction, output=ARGS.output, view=ARGS.view)
