#!/usr/bin/env python

from sys import argv, stderr
import argparse
from makefile2dot import makefile2dot

PARSER = argparse.ArgumentParser(description="Stuff")
PARSER.add_argument('--direction', dest='direction', default="BT",
                    help="direction to draw graph ('BT', 'TB', 'LR', or 'RL')")

ARGS = PARSER.parse_args()

makefile2dot(direction=ARGS.direction)
